#!/bin/bash
# Compile all "other" submodule figures generated by plot_other.py.

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"
RESULTS_DIR="$SCRIPT_DIR/results"
mkdir -p "$RESULTS_DIR"

PYTHON="../.venv/bin/python"
BASENAMES=(
  "model_other_convblock"
  "model_other_upblock"
  "model_other_fuse"
  "model_other_stop_head"
)

echo "[1/3] generating .tex files ..."
"$PYTHON" plot_other.py

cd "$RESULTS_DIR"

echo "[2/3] compiling PDFs ..."
for base in "${BASENAMES[@]}"; do
  echo "  - ${base}.tex"
  pdflatex -interaction=nonstopmode "${base}.tex" >/dev/null
done

echo "[3/3] exporting PNGs ..."
for base in "${BASENAMES[@]}"; do
  pdftoppm -r 300 -png "${base}.pdf" "${base}_page" >/dev/null
  mv "${base}_page-1.png" "${base}.png"
  rm -f "${base}.aux" "${base}.log"
done

echo "done -> article/results/model_other_*.png"
